### ISSUE TITLE
can't reach server....

### ISSUE THREAD

**Issue by bvdbos** [athombv/nl.buienradar#12] opened 2016-09-20 18:05 UTC
https://github.com/athombv/nl.buienradar/blob/master/node_modules/buienradar/lib/buienradar.js#L85
the gps-domain is decrepated. You should use gadgets.buienradar.nl

**Comment by BasKiers** [comment] 2016-09-20 19:07
gps should redirect but set it to gadgets now. The issue is fixed in v2.0.2

**Closed by BasKiers** 2016-09-20 19:07 UTC
