### ISSUE TITLE
Version history

### ISSUE THREAD

**Issue by Heki2017** [athombv/nl.buienradar#20] opened 2017-08-19 06:16 UTC
First of all thanks all for the good work on buienradar app for Homey. As a new version came available I would like to know before installing what has changed/added. Is it possible to keep a (short) version history in the readme file ? 

Thanks for putting your time and effort in this nice app

**Comment by jeroenvollenbrock** [comment] 2017-10-30 22:51
Closing as duplicate of https://github.com/athombv/homey/issues/1915

**Closed by jeroenvollenbrock** 2017-10-30 22:51 UTC
